apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-prod
  namespace: argocd-prod
spec:
  project: default
  source:
    repoURL: https://github.com/xavero-evandro/devops-workshop-gitops
    targetRevision: main
    path: apps/workshop/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: workshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
