apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yml

images:
  - name: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-backend
    newName: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-backend
    newTag: dev-0001
  - name: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-frontend
    newName: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-frontend
    newTag: dev-0001
